# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=10.15.0-alpine'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-10.15.0-alpine'
  # 10.10.0 is tagged :current
  - '--tag=gcr.io/$PROJECT_ID/npm:latest'
  - '.'

- name: 'gcr.io/$PROJECT_ID/npm:node-10.15.0-alpine'
  args: ['version']

# Test the examples with :latest
- name: 'gcr.io/$PROJECT_ID/npm:latest'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm:latest'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'

images:
- 'gcr.io/$PROJECT_ID/npm:latest'
